/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/camera.glb --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/camera.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={19.16} position={[0.18, 1.54, 1.68]} rotation={[-0.53, 0.03, 0.03]} />
      </group>
    </group>
  )
}

useGLTF.preload('/camera.glb')
