/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/bookshelf.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Bookshelf(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/bookshelf.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='bookcase'
          geometry={nodes.bookcase.geometry}
          material={materials['Material #50']}
          position={[-1.83, 1.4, 0.38]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.03}
        />
        <group
          name='Cube001'
          position={[-1.63, 0.83, 0.21]}
          rotation={[0, 0.03, 0.33]}
          scale={[0.01, 0.12, 0.09]}>
          <mesh
            name='Cube001_1'
            geometry={nodes.Cube001_1.geometry}
            material={materials.Material}
          />
          <mesh
            name='Cube001_2'
            geometry={nodes.Cube001_2.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name='Cube001_3'
            geometry={nodes.Cube001_3.geometry}
            material={materials['Material.007']}
          />
        </group>
        <group
          name='Cube003'
          position={[-1.65, 0.83, -0.16]}
          rotation={[0, -0.35, 0.33]}
          scale={[0.01, 0.12, 0.09]}>
          <mesh
            name='Cube002_1'
            geometry={nodes.Cube002_1.geometry}
            material={materials.Material}
          />
          <mesh
            name='Cube002_2'
            geometry={nodes.Cube002_2.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name='Cube002_3'
            geometry={nodes.Cube002_3.geometry}
            material={materials['Material.007']}
          />
        </group>
        <group
          name='Cube004'
          position={[-1.62, 1.16, 0.2]}
          rotation={[0, 0.02, 0.33]}
          scale={[0.01, 0.1, 0.07]}>
          <mesh
            name='Cube003_1'
            geometry={nodes.Cube003_1.geometry}
            material={materials.Material}
          />
          <mesh
            name='Cube003_2'
            geometry={nodes.Cube003_2.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name='Cube003_3'
            geometry={nodes.Cube003_3.geometry}
            material={materials['Material.007']}
          />
        </group>
        <group
          name='Cube'
          position={[-1.62, 0.81, 0.54]}
          rotation={[0, 0.19, 0.33]}
          scale={[0.01, 0.12, 0.09]}>
          <mesh
            name='Cube_1'
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            name='Cube_2'
            geometry={nodes.Cube_2.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name='Cube_3'
            geometry={nodes.Cube_3.geometry}
            material={materials['Material.007']}
          />
        </group>
        <group
          name='Cube002'
          position={[-1.63, 1.17, -0.16]}
          rotation={[0, -0.26, 0.33]}
          scale={[0.01, 0.12, 0.09]}>
          <mesh
            name='Cube004_1'
            geometry={nodes.Cube004_1.geometry}
            material={materials.Material}
          />
          <mesh
            name='Cube004_2'
            geometry={nodes.Cube004_2.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name='Cube004_3'
            geometry={nodes.Cube004_3.geometry}
            material={materials['Material.007']}
          />
        </group>
        <group
          name='Cube006'
          position={[-1.63, 1.17, 0.52]}
          rotation={[0, 0.25, 0.33]}
          scale={[0.01, 0.12, 0.09]}>
          <mesh
            name='Cube008'
            geometry={nodes.Cube008.geometry}
            material={materials.Material}
          />
          <mesh
            name='Cube008_1'
            geometry={nodes.Cube008_1.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name='Cube008_2'
            geometry={nodes.Cube008_2.geometry}
            material={materials['Material.007']}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/bookshelf.glb');
