/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/Portfolio2_.glb --keepnames
*/

import React, { useEffect, useRef } from 'react';
import {
  useGLTF,
  PerspectiveCamera,
  useAnimations,
  Environment,
  Sparkles,
} from '@react-three/drei';
import { PresentationControls } from '@react-three/drei';
import * as THREE from 'three';

export function Portfolio(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/Portfolio2_.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    setTimeout(() => {
      actions['Projects'].setLoop(THREE.LoopOnce);
      actions['Projects'].clampWhenFinished = true;
      actions['Projects'].play();
    }, 2000);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        {/* <group
          name='Spot001'
          position={[0.31, 5.14, 3.94]}
          rotation={[-0.61, 0, -0.66]}
          scale={0.62}
        /> */}
        <PerspectiveCamera
          name='Camera'
          makeDefault={true}
          far={1000}
          near={0.1}
          fov={25.92}
          position={[0.18, 1.54, 1.68]}
          rotation={[-0.53, 0.03, 0.03]}
        />
        {/* <directionalLight
          name='Spot'
          intensity={1}
          decay={2}
          color='#d0f0ff'
          position={[2.06, 5.14, 0.89]}
          rotation={[-0.78, 1, -0.99]}
          scale={0.62}>
          <group position={[0, 0, -1]} />
        </directionalLight> */}
        {/* <pointLight
          name='Point'
          intensity={4}
          decay={2}
          color='#ffbf5a'
          position={[-1.85, 1.79, 0.73]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name='Point001'
          intensity={4}
          decay={2}
          color='#ffbf5a'
          position={[-1.85, 1.79, 0.36]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name='Point002'
          intensity={4}
          decay={2}
          color='#ffbf5a'
          position={[-1.85, 1.79, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        /> */}
        <PresentationControls
          global
          rotation={[-0.15, 0.17, 0]}
          polar={[-0.4, 0.2]}
          azimuth={[-0.5, 0.5]}
          config={{ mass: 2, tension: 400 }}
          snap={{ mass: 4, tension: 400 }}>
          <Environment preset='night' />
          <rectAreaLight
            width={7}
            height={10}
            intensity={10}
            color={'#fff'}
            rotation={[Math.PI / 2, Math.PI, 0]}
            position={[0.37, 10, 1.87]}
          />
          <rectAreaLight
            width={5}
            height={0.3}
            color={'#00f'}
            intensity={15}
            position={[-6.15, 4.37, 3.56]}
            rotation={[-Math.PI / 2, 0, 0]}
            // position={[x, y, z]}
          />
          <rectAreaLight
            width={5}
            height={0.3}
            color={'#00f'}
            intensity={15}
            position={[-6.15, 4.37, 2.44]}
            rotation={[-Math.PI / 2, 0, 0]}
            // position={[x, y, z]}
          />
          <rectAreaLight
            width={5}
            height={0.3}
            color={'#00f'}
            intensity={15}
            position={[-6.15, 4.37, 1.32]}
            rotation={[-Math.PI / 2, 0, 0]}
            // position={[x, y, z]}
          />
          <Sparkles speed={0.5} scale={[8, 5, 8]} count={200} />
          <group
            name='White_Board'
            position={[0.32, 2.02, -2.68]}
            rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              name='Plane002'
              geometry={nodes.Plane002.geometry}
              material={materials['Alluminum.003']}
            />
            <mesh
              name='Plane002_1'
              geometry={nodes.Plane002_1.geometry}
              material={materials['White Board.003']}
            />
            <mesh
              name='Black_Marker_on_Whiteboard_01'
              geometry={nodes.Black_Marker_on_Whiteboard_01.geometry}
              material={materials['Black Marker on Whiteboard 01.003']}
              position={[0.26, 0.02, 0.31]}
              rotation={[0, -0.04, 0]}
              scale={0.77}
            />
            <mesh
              name='Black_Marker_on_Whiteboard_01001'
              geometry={nodes.Black_Marker_on_Whiteboard_01001.geometry}
              material={materials['Black Marker on Whiteboard 01.002']}
              position={[-0.07, 2.99, 1.57]}
              rotation={[-Math.PI / 2, -0.04, 0]}
              scale={0.77}
            />
            <mesh
              name='Purple_Marker_on_Whiteboard'
              geometry={nodes.Purple_Marker_on_Whiteboard.geometry}
              material={materials['Purple Marker on Whiteboard.003']}
              position={[-0.49, 0.03, -0.16]}
              scale={1.04}
            />
            <mesh
              name='Red_Marker_on_Whiteboard'
              geometry={nodes.Red_Marker_on_Whiteboard.geometry}
              material={materials['Red Marker on Whiteboard.003']}
              position={[0.67, 0.02, -0.11]}
              rotation={[0, 0.06, 0]}
            />
            <mesh
              name='Red_Marker_on_Whiteboard002'
              geometry={nodes.Red_Marker_on_Whiteboard002.geometry}
              material={materials['Black Mark']}
              position={[0.27, 0.04, 0.48]}
              rotation={[0, 0.06, 0]}
              scale={[1.99, 1, 2.49]}
            />
          </group>
          <group
            name='Cube007'
            position={[-0.05, 0.47, -0.1]}
            rotation={[Math.PI / 2, 0, 0.9]}
            scale={0.01}>
            <mesh
              name='Cube007_1'
              geometry={nodes.Cube007_1.geometry}
              material={materials.black_plastic}
            />
            <mesh
              name='Cube007_2'
              geometry={nodes.Cube007_2.geometry}
              material={materials.white}
            />
            <mesh
              name='Cube007_3'
              geometry={nodes.Cube007_3.geometry}
              material={materials.blue}
            />
            <mesh
              name='Cube007_4'
              geometry={nodes.Cube007_4.geometry}
              material={materials.orange}
            />
            <mesh
              name='Cube007_5'
              geometry={nodes.Cube007_5.geometry}
              material={materials['red.001']}
            />
            <mesh
              name='Cube007_6'
              geometry={nodes.Cube007_6.geometry}
              material={materials.green}
            />
            <mesh
              name='Cube007_7'
              geometry={nodes.Cube007_7.geometry}
              material={materials.yellow}
            />
          </group>
          <mesh
            name='Experience'
            geometry={nodes.Experience.geometry}
            material={materials.Toy}
            position={[-0.24, 0.47, 0.12]}
            rotation={[0, -1.43, 0]}
            scale={0.19}
          />
          <mesh
            name='Notebook'
            geometry={nodes.Notebook.geometry}
            material={materials['Default.001']}
            position={[0.95, 0.48, 0.58]}
            rotation={[Math.PI / 2, 0, 1.71]}
          />
          <mesh
            name='Resume'
            geometry={nodes.Resume.geometry}
            material={materials.Toy}
            position={[0.04, 0.53, -0.09]}
            rotation={[-1.24, -1.28, -1.23]}
            scale={0.19}
          />
          <mesh
            name='Projects'
            geometry={nodes.Projects.geometry}
            material={materials.Toy}
            position={[-0.12, 0.53, -0.05]}
            rotation={[1.02, -1.34, 1.01]}
            scale={0.19}
          />
          <group name='Plane' position={[0, 0.47, 0]}>
            <mesh
              name='Plane_1'
              geometry={nodes.Plane_1.geometry}
              material={materials.BLACK}
            />
            <mesh
              name='Plane_2'
              geometry={nodes.Plane_2.geometry}
              material={materials.red}
            />
            <mesh
              name='Plane_3'
              geometry={nodes.Plane_3.geometry}
              material={materials.glass}
            />
          </group>
          <group
            name='Laptop'
            position={[0.48, 0.6, -0.13]}
            rotation={[1.32, -0.07, 0.26]}
            scale={[0.19, 0.1, 0.13]}>
            <mesh
              name='Plane001'
              geometry={nodes.Plane001.geometry}
              material={materials.BLACK}
            />
            <mesh
              name='Plane001_1'
              geometry={nodes.Plane001_1.geometry}
              material={materials['Material.002']}
            />
            <mesh
              name='Plane001_2'
              geometry={nodes.Plane001_2.geometry}
              material={materials['Material.003']}
            />
          </group>
          <mesh
            name='bookcase'
            geometry={nodes.bookcase.geometry}
            material={materials['Material #50']}
            position={[-1.73, 1.4, 0.36]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.03}
          />
          <group
            name='Cube001'
            position={[-1.63, 0.48, 0.21]}
            rotation={[0, 0.03, 0.33]}
            scale={[0.01, 0.12, 0.09]}>
            <mesh
              name='Cube001_1'
              geometry={nodes.Cube001_1.geometry}
              material={materials.Material}
            />
            <mesh
              name='Cube001_2'
              geometry={nodes.Cube001_2.geometry}
              material={materials['Material.006']}
            />
            <mesh
              name='Cube001_3'
              geometry={nodes.Cube001_3.geometry}
              material={materials['Material.007']}
            />
          </group>
          <group
            name='Cube003'
            position={[-1.65, 0.83, -0.16]}
            rotation={[0, -0.06, 0.33]}
            scale={[0.01, 0.12, 0.09]}>
            <mesh
              name='Cube002'
              geometry={nodes.Cube002.geometry}
              material={materials.Material}
            />
            <mesh
              name='Cube002_1'
              geometry={nodes.Cube002_1.geometry}
              material={materials['Material.006']}
            />
            <mesh
              name='Cube002_2'
              geometry={nodes.Cube002_2.geometry}
              material={materials['Material.007']}
            />
          </group>
          <group
            name='Cube004'
            position={[-1.62, 1.16, 0.2]}
            rotation={[0, 0.02, 0.33]}
            scale={[0.01, 0.1, 0.07]}>
            <mesh
              name='Cube003_1'
              geometry={nodes.Cube003_1.geometry}
              material={materials.Material}
            />
            <mesh
              name='Cube003_2'
              geometry={nodes.Cube003_2.geometry}
              material={materials['Material.006']}
            />
            <mesh
              name='Cube003_3'
              geometry={nodes.Cube003_3.geometry}
              material={materials['Material.007']}
            />
          </group>
          <mesh
            name='Cube005'
            geometry={nodes.Cube005.geometry}
            material={materials.BLACK}
            position={[0.77, 0.94, -0.01]}
            scale={[2.73, 1, 2.73]}
          />
          <mesh
            name='Astro_Lighting_Parma_160_Wall'
            geometry={nodes.Astro_Lighting_Parma_160_Wall.geometry}
            material={materials.Astro_Lighting_Parma_160_Wall_mtl_1}
            position={[-1.92, 1.79, 0.73]}
            rotation={[-Math.PI, Math.PI / 2, 0]}
            scale={0.01}
          />
          <group
            name='Cube'
            position={[-1.69, 0.81, 0.54]}
            rotation={[0, 0.19, 0.33]}
            scale={[0.01, 0.12, 0.09]}>
            <mesh
              name='Cube_1'
              geometry={nodes.Cube_1.geometry}
              material={materials.Material}
            />
            <mesh
              name='Cube_2'
              geometry={nodes.Cube_2.geometry}
              material={materials['Material.006']}
            />
            <mesh
              name='Cube_3'
              geometry={nodes.Cube_3.geometry}
              material={materials['Material.007']}
            />
          </group>
          <mesh
            name='Text_0_001'
            geometry={nodes.Text_0_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_1_001'
            geometry={nodes.Text_1_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_2_001'
            geometry={nodes.Text_2_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_3_001'
            geometry={nodes.Text_3_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_4_001'
            geometry={nodes.Text_4_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_5_001'
            geometry={nodes.Text_5_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_6_001'
            geometry={nodes.Text_6_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_7_001'
            geometry={nodes.Text_7_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_8_001'
            geometry={nodes.Text_8_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_9_001'
            geometry={nodes.Text_9_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_A_001'
            geometry={nodes.Text_A_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_B_001'
            geometry={nodes.Text_B_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_C_001'
            geometry={nodes.Text_C_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_D_001'
            geometry={nodes.Text_D_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_E_001'
            geometry={nodes.Text_E_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_F_001'
            geometry={nodes.Text_F_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_G_001'
            geometry={nodes.Text_G_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_H_001'
            geometry={nodes.Text_H_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_I_001'
            geometry={nodes.Text_I_001.geometry}
            material={materials.Toy}
            position={[5.66, 0.8, -0.07]}
          />
          <mesh
            name='Text_J_001'
            geometry={nodes.Text_J_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_K_001'
            geometry={nodes.Text_K_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_L__001'
            geometry={nodes.Text_L__001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_M_001'
            geometry={nodes.Text_M_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_N_001'
            geometry={nodes.Text_N_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_O_001'
            geometry={nodes.Text_O_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_P_001'
            geometry={nodes.Text_P_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_Q_001'
            geometry={nodes.Text_Q_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_R_001'
            geometry={nodes.Text_R_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_S_001'
            geometry={nodes.Text_S_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_T_001'
            geometry={nodes.Text_T_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_U_001'
            geometry={nodes.Text_U_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_V_001'
            geometry={nodes.Text_V_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_W_001'
            geometry={nodes.Text_W_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_X_001'
            geometry={nodes.Text_X_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_Y_001'
            geometry={nodes.Text_Y_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
          <mesh
            name='Text_Z_001'
            geometry={nodes.Text_Z_001.geometry}
            material={materials.Toy}
            position={[6.43, 0.65, 0.07]}
          />
        </PresentationControls>
      </group>
    </group>
  );
}

useGLTF.preload('/Portfolio2_.glb');
