/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/resumepaper.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function ResumePaper(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/resumepaper.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Plane001'
          geometry={nodes.Plane001.geometry}
          material={materials.rES3}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/resumepaper.glb');
